//! Generated by scripts/gen-font.py - do not edit by hand.
//! Specimen glyph outlines from assets/font/*.svg, rasterised into a
//! 32x56 coverage mask (4x the cell they are drawn at), one byte
//! of area coverage per sample, stored glyph after glyph in font_data.bin in
//! the order of `chars`. src/core/font.zig resamples the mask to the requested
//! size.

pub const cell_width: u32 = 8;
pub const cell_height: u32 = 14;
pub const supersample: u32 = 4;
pub const mask_width: u32 = 32;
pub const mask_height: u32 = 56;
pub const glyph_bytes: usize = mask_width * mask_height;

pub const chars = [_]u8{ 35, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 65, 66, 67, 68, 69, 70, 215 };
const mask = @embedFile("font_data.bin");

comptime {
    if (mask.len != chars.len * glyph_bytes) @compileError("font_data.bin does not match chars");
}

/// Row-major coverage samples for `char`, `mask_width` bytes per row.
pub fn find(char: u8) ?*const [glyph_bytes]u8 {
    for (chars, 0..) |candidate, i| {
        if (candidate == char) return mask[i * glyph_bytes ..][0..glyph_bytes];
    }
    return null;
}
