#!/usr/bin/env python3
"""Bake the specimen glyphs in assets/font/ into src/core/font_data.bin plus
the src/core/font_data.zig header that describes it.

The glyphs are SVG outlines, but the renderer draws from a coverage mask: each
outline is rasterised at OVERSAMPLE * SUPERSAMPLE times the cell it is drawn at
and box filtered down to SUPERSAMPLE, so every mask sample is an 8-bit area
coverage rather than a thresholded bit. src/core/font.zig resamples that mask
to the requested size with exact area weights (or bilinear when magnifying),
which is what gives the strokes a smooth, proportional anti-aliased edge.

Every glyph is placed by the same rule - cap top on CAP_TOP, baseline on
BASELINE - so the set shares one scale and one baseline instead of each outline
being stretched to its own bounding box.

Usage: python3 scripts/gen-font.py
Requires rsvg-convert and Pillow.
"""

import io
import re
import subprocess
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets" / "font"
OUT_BIN = ROOT / "src" / "core" / "font_data.bin"
OUT_ZIG = ROOT / "src" / "core" / "font_data.zig"
GLYPHS = "#0123456789ABCDEF\u00d7"
FILENAMES = {"#": "hash", "\u00d7": "times"}

CELL_WIDTH = 8
CELL_HEIGHT = 14
SUPERSAMPLE = 4
OVERSAMPLE = 8
MASK_WIDTH = CELL_WIDTH * SUPERSAMPLE
MASK_HEIGHT = CELL_HEIGHT * SUPERSAMPLE
RASTER_WIDTH = MASK_WIDTH * OVERSAMPLE
RASTER_HEIGHT = MASK_HEIGHT * OVERSAMPLE

# The assets share a 29x44 design box in which the cap top is at CAP_TOP and the
# baseline at BASELINE. The box maps to the full mask width, and the baseline is
# pinned to BASELINE_MASK, matching the mask the renderer was tuned against.
DESIGN_WIDTH = 29.0
CAP_TOP = 5.0
BASELINE = 38.0
BASELINE_MASK = 46.0


def glyph_mask(char):
    """Rasterise one asset into a coverage mask, one byte per sample."""
    source = (ASSETS / f"{FILENAMES.get(char, char)}.svg").read_text()
    paths = re.findall(r"<path[^>]*/>", source)
    if not paths:
        raise SystemExit(f"{char}: no paths in asset")

    scale = MASK_WIDTH / DESIGN_WIDTH
    translate = BASELINE_MASK - BASELINE * scale
    wrapped = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{MASK_WIDTH}" '
        f'height="{MASK_HEIGHT}" viewBox="0 0 {MASK_WIDTH} {MASK_HEIGHT}">'
        f'<g fill="#fff" transform="translate(0,{translate:.4f}) '
        f'scale({scale:.6f})">{"".join(paths)}</g></svg>'
    )
    rendered = subprocess.run(
        ["rsvg-convert", "-w", str(RASTER_WIDTH), "-h", str(RASTER_HEIGHT)],
        input=wrapped.encode(), capture_output=True, check=True,
    ).stdout

    with Image.open(io.BytesIO(rendered)) as image:
        # Coverage lives in alpha: the fill is white on transparent.
        alpha = image.convert("RGBA").getchannel("A")
        reduced = alpha.reduce(OVERSAMPLE)
        return reduced.tobytes()


def main():
    if len(GLYPHS) != len(set(GLYPHS)):
        raise SystemExit("duplicate characters in GLYPHS")
    if any(ord(char) > 0xFF for char in GLYPHS):
        raise SystemExit("glyph characters must fit in one byte")

    blob = b"".join(glyph_mask(char) for char in GLYPHS)
    OUT_BIN.write_bytes(blob)

    chars = ", ".join(str(ord(char)) for char in GLYPHS)
    OUT_ZIG.write_text(f"""//! Generated by scripts/gen-font.py - do not edit by hand.
//! Specimen glyph outlines from assets/font/*.svg, rasterised into a
//! {MASK_WIDTH}x{MASK_HEIGHT} coverage mask ({SUPERSAMPLE}x the cell they are drawn at), one byte
//! of area coverage per sample, stored glyph after glyph in font_data.bin in
//! the order of `chars`. src/core/font.zig resamples the mask to the requested
//! size.

pub const cell_width: u32 = {CELL_WIDTH};
pub const cell_height: u32 = {CELL_HEIGHT};
pub const supersample: u32 = {SUPERSAMPLE};
pub const mask_width: u32 = {MASK_WIDTH};
pub const mask_height: u32 = {MASK_HEIGHT};
pub const glyph_bytes: usize = mask_width * mask_height;

pub const chars = [_]u8{{ {chars} }};
const mask = @embedFile("font_data.bin");

comptime {{
    if (mask.len != chars.len * glyph_bytes) @compileError("font_data.bin does not match chars");
}}

/// Row-major coverage samples for `char`, `mask_width` bytes per row.
pub fn find(char: u8) ?*const [glyph_bytes]u8 {{
    for (chars, 0..) |candidate, i| {{
        if (candidate == char) return mask[i * glyph_bytes ..][0..glyph_bytes];
    }}
    return null;
}}
""")
    print(f"wrote {OUT_BIN.relative_to(ROOT)} ({len(blob)} bytes) and {OUT_ZIG.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
