#!/usr/bin/env python3
"""Bake a small monospace bitmap font into src/core/font_data.zig.

The loupe badge only ever prints hex colours and pixel dimensions, so we bake
just the glyphs those strings need. Rendering the glyphs with PIL at build-of-
this-script time gives far better shapes than hand-typed 5x7 matrices, and the
result is a dependency-free zig source file.

The mask is stored at SUPERSAMPLE times the cell size it is drawn at, as a plain
ink mask, and src/core/font.zig box-filters it down when drawing. That is what
makes the text smooth: scaling a 1x ink mask with nearest-neighbour (what this
used to do) gives every stroke a different width, which reads as jagged.

Usage: python3 tools/gen-font.py > src/core/font_data.zig
"""

from PIL import Image, ImageDraw, ImageFont

FONT_CANDIDATES = [
    "/usr/share/fonts/TTF/JetBrainsMonoNerdFontMono-Regular.ttf",
    "/usr/share/fonts/noto/NotoSansMono-Regular.ttf",
    "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]
POINT_SIZE = 13
GLYPHS = " #0123456789ABCDEFPX\u00d7px"
CELL_WIDTH = 8
CELL_HEIGHT = 14
SUPERSAMPLE = 4
THRESHOLD = 100


def load_font():
    for path in FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, POINT_SIZE * SUPERSAMPLE)
        except OSError:
            continue
    raise SystemExit("no usable monospace font found")


def main():
    font = load_font()
    ascent, descent = font.getmetrics()
    mask_width = CELL_WIDTH * SUPERSAMPLE
    mask_height = CELL_HEIGHT * SUPERSAMPLE

    rows = []
    for ch in GLYPHS:
        image = Image.new("L", (mask_width * 2, mask_height * 2), 0)
        draw = ImageDraw.Draw(image)
        bbox = draw.textbbox((0, 0), ch, font=font)
        width = bbox[2] - bbox[0]
        height = bbox[3] - bbox[1]
        x = (mask_width - width) // 2 - bbox[0]
        y = (ascent - height) // 2 - bbox[1]
        draw.text((x, y), ch, fill=255, font=font)

        cell = []
        for row in range(mask_height):
            bits = 0
            for column in range(mask_width):
                if image.getpixel((column, row)) >= THRESHOLD:
                    bits |= 1 << (mask_width - 1 - column)
            cell.append(bits)
        rows.append((ch, cell))

    print("//! Generated by tools/gen-font.py - do not edit by hand.")
    print("//! JetBrains Mono / Noto Sans Mono derived glyph masks,")
    print("//! rendered at point size", POINT_SIZE * SUPERSAMPLE, "and thresholded into a")
    print(f"//! {mask_width}x{mask_height} ink mask, which src/core/font.zig box filters")
    print("//! down to the requested size. cell_width/cell_height are the size the")
    print("//! mask is drawn at; the mask is supersample times larger.")
    print()
    print(f"pub const cell_width: u32 = {CELL_WIDTH};")
    print(f"pub const cell_height: u32 = {CELL_HEIGHT};")
    print(f"pub const supersample: u32 = {SUPERSAMPLE};")
    print(f"pub const mask_width: u32 = {mask_width};")
    print(f"pub const mask_height: u32 = {mask_height};")
    print()
    print("pub const Glyph = struct {")
    print("    char: u8,")
    print("    /// One bit per ink sample, most significant bit leftmost.")
    print("    rows: [mask_height]u32,")
    print("};")
    print()
    print("pub const glyphs = [_]Glyph{")
    for ch, cell in rows:
        shown = ch if ch != " " else "space"
        print(f'    // "{shown}"')
        print("    .{")
        print(f"        .char = {ord(ch)},")
        print("        .rows = .{")
        for offset in range(0, mask_height, 4):
            chunk = ", ".join(f"0x{value:08X}" for value in cell[offset:offset + 4])
            print(f"            {chunk},")
        print("        },")
        print("    },")
    print("};")
    print()
    print("pub fn find(char: u8) ?*const Glyph {")
    print("    for (&glyphs) |*glyph| {")
    print("        if (glyph.char == char) return glyph;")
    print("    }")
    print("    return null;")
    print("}")


if __name__ == "__main__":
    main()