#!/usr/bin/env python3
"""Bake the specimen glyphs in assets/font/ into src/core/font_data.zig.

The glyphs are SVG outlines, but the renderer draws from a plain ink mask, so
each outline is rasterised at SUPERSAMPLE times the cell it is drawn at, then
thresholded to one bit per sample. src/core/font.zig box filters that mask down
when drawing, which is what gives the strokes a proportional anti-aliased edge.

Every glyph is placed by the same rule - cap top on CAP_TOP, baseline on
BASELINE - so the set shares one scale and one baseline instead of each outline
being stretched to its own bounding box.

Usage: python3 tools/gen-font.py > src/core/font_data.zig
Requires rsvg-convert and Pillow.
"""

import io
import re
import subprocess
import sys
from pathlib import Path

from PIL import Image

ASSETS = Path(__file__).resolve().parent.parent / "assets" / "font"
GLYPHS = "#0123456789ABCDEF\u00d7"
FILENAMES = {"#": "hash", "\u00d7": "times"}

CELL_WIDTH = 8
CELL_HEIGHT = 14
SUPERSAMPLE = 4
MASK_WIDTH = CELL_WIDTH * SUPERSAMPLE
MASK_HEIGHT = CELL_HEIGHT * SUPERSAMPLE

# The assets share a 29x44 design box in which the cap top is at CAP_TOP and the
# baseline at BASELINE. The box maps to the full mask width, and the baseline is
# pinned to BASELINE_MASK, matching the mask the renderer was tuned against.
DESIGN_WIDTH = 29.0
CAP_TOP = 5.0
BASELINE = 38.0
BASELINE_MASK = 46.0
THRESHOLD = 128


def glyph_mask(char):
    """Rasterise one asset into an ink mask, one bit per sample."""
    source = (ASSETS / f"{FILENAMES.get(char, char)}.svg").read_text()
    paths = re.findall(r"<path[^>]*/>", source)
    if not paths:
        raise SystemExit(f"{char}: no paths in asset")

    scale = MASK_WIDTH / DESIGN_WIDTH
    translate = BASELINE_MASK - BASELINE * scale
    wrapped = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{MASK_WIDTH}" '
        f'height="{MASK_HEIGHT}" viewBox="0 0 {MASK_WIDTH} {MASK_HEIGHT}">'
        f'<g fill="#fff" transform="translate(0,{translate:.4f}) '
        f'scale({scale:.6f})">{"".join(paths)}</g></svg>'
    )
    rendered = subprocess.run(
        ["rsvg-convert", "-w", str(MASK_WIDTH), "-h", str(MASK_HEIGHT)],
        input=wrapped.encode(), capture_output=True, check=True,
    ).stdout

    with Image.open(io.BytesIO(rendered)) as image:
        gray = image.convert("L")
        rows = []
        for y in range(MASK_HEIGHT):
            bits = 0
            for x in range(MASK_WIDTH):
                if gray.getpixel((x, y)) >= THRESHOLD:
                    bits |= 1 << (MASK_WIDTH - 1 - x)
            rows.append(bits)
    return rows


def main():
    if len(GLYPHS) != len(set(GLYPHS)):
        raise SystemExit("duplicate characters in GLYPHS")

    print("//! Generated by tools/gen-font.py - do not edit by hand.")
    print("//! Specimen glyph outlines from assets/font/*.svg, rasterised at")
    print(f"//! {SUPERSAMPLE}x into a {MASK_WIDTH}x{MASK_HEIGHT} ink mask, which src/core/font.zig")
    print("//! box filters down to the requested size. cell_width/cell_height are the")
    print("//! size the mask is drawn at; the mask is supersample times larger.")
    print()
    print(f"pub const cell_width: u32 = {CELL_WIDTH};")
    print(f"pub const cell_height: u32 = {CELL_HEIGHT};")
    print(f"pub const supersample: u32 = {SUPERSAMPLE};")
    print(f"pub const mask_width: u32 = {MASK_WIDTH};")
    print(f"pub const mask_height: u32 = {MASK_HEIGHT};")
    print()
    print("pub const Glyph = struct {")
    print("    char: u8,")
    print("    /// One bit per ink sample, most significant bit leftmost.")
    print("    rows: [mask_height]u32,")
    print("};")
    print()
    print("pub const glyphs = [_]Glyph{")
    for char in GLYPHS:
        rows = glyph_mask(char)
        shown = char if char != " " else "space"
        print(f'    // "{shown}"')
        print("    .{")
        print(f"        .char = {ord(char)},")
        print("        .rows = .{")
        for offset in range(0, MASK_HEIGHT, 4):
            chunk = ", ".join(f"0x{value:08X}" for value in rows[offset:offset + 4])
            print(f"            {chunk},")
        print("        },")
        print("    },")
    print("};")
    print()
    print("pub fn find(char: u8) ?*const Glyph {")
    print("    for (&glyphs) |*glyph| {")
    print("        if (glyph.char == char) return glyph;")
    print("    }")
    print("    return null;")
    print("}")


if __name__ == "__main__":
    sys.exit(main())
