#!/usr/bin/env python3
"""Bake a small monospace bitmap font into src/core/font_data.zig.

The loupe badge only ever prints hex colours and pixel dimensions, so we bake
just the glyphs those strings need. Rendering the glyphs with PIL at build-of-
this-script time gives far better shapes than hand-typed 5x7 matrices, and the
result is a dependency-free zig source file.

Usage: python3 tools/gen-font.py > src/core/font_data.zig
"""

from PIL import Image, ImageDraw, ImageFont

FONT_CANDIDATES = [
    "/usr/share/fonts/TTF/JetBrainsMonoNerdFontMono-Regular.ttf",
    "/usr/share/fonts/noto/NotoSansMono-Regular.ttf",
    "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]
POINT_SIZE = 13
GLYPHS = " #0123456789ABCDEFPX\u00d7px"
CELL_WIDTH = 8
CELL_HEIGHT = 14
THRESHOLD = 110


def load_font():
    for path in FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, POINT_SIZE)
        except OSError:
            continue
    raise SystemExit("no usable monospace font found")


def main():
    font = load_font()
    ascent, descent = font.getmetrics()
    rows = []
    for ch in GLYPHS:
        image = Image.new("L", (CELL_WIDTH * 4, CELL_HEIGHT * 2), 0)
        draw = ImageDraw.Draw(image)
        bbox = draw.textbbox((0, 0), ch, font=font)
        width = bbox[2] - bbox[0]
        height = bbox[3] - bbox[1]
        x = (CELL_WIDTH - width) // 2 - bbox[0]
        y = (ascent - height) // 2 - bbox[1]
        draw.text((x, y), ch, fill=255, font=font)
        cell = []
        for row in range(CELL_HEIGHT):
            bits = 0
            for column in range(CELL_WIDTH):
                value = image.getpixel((column, row))
                if value >= THRESHOLD:
                    bits |= 1 << (CELL_WIDTH - 1 - column)
            cell.append(bits)
        rows.append((ch, cell))

    print("//! Generated by tools/gen-font.py - do not edit by hand.")
    print("//! JetBrains Mono / Noto Sans Mono derived bitmap glyphs,")
    print("//! rendered at point size", POINT_SIZE, "into a",
          f"{CELL_WIDTH}x{CELL_HEIGHT}", "cell.")
    print()
    print(f"pub const cell_width: u32 = {CELL_WIDTH};")
    print(f"pub const cell_height: u32 = {CELL_HEIGHT};")
    print()
    print("pub const Glyph = struct {")
    print("    char: u8,")
    print("    rows: [cell_height]u8,")
    print("};")
    print()
    print(f"pub const glyphs = [_]Glyph{{")
    for ch, cell in rows:
        shown = ch if ch != " " else "space"
        values = ", ".join(f"0x{value:02X}" for value in cell)
        print(f'    // "{shown}"')
        print(f"    .{{ .char = {ord(ch)}, .rows = .{{ {values} }} }},")
    print("};")
    print()
    print("pub fn find(char: u8) ?*const Glyph {")
    print("    for (&glyphs) |*glyph| {")
    print("        if (glyph.char == char) return glyph;")
    print("    }")
    print("    return null;")
    print("}")


if __name__ == "__main__":
    main()